# Use root/example as user/password credentials
version: '3.1'

services:
  spring-boot-app:
    image: spring-app
    container_name: springboot-container
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - my-network
    ports:
      - 8081:8080
    environment:
      - spring.datasource.url=jdbc:mysql://host.docker.internal:3306/moneymanagement
      - spring.datasource.username=developer
      - spring.datasource.password=adf14500

networks:
  my-network: