# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: adf14500
    ports:
      - 3305:3306

  spring-boot-app:
    image: spring-app
    container_name: springboot-container
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8081:8080
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/moneymanagement
      - spring.datasource.username=root
      - spring.datasource.password=adf14500
    depends_on:
      - db